# compose
version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgressql/data
    environment:
      - POSTGRES_DB=my_newdb2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_postgres
    ports:
      - "54320:54320"
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
