# Generated by Django 3.2.15 on 2022-08-31 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api', '0002_auto_20220831_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
