# Generated by Django 3.2.15 on 2022-08-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api', '0003_auto_20220831_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
