# Generated by Django 3.2.15 on 2022-08-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api', '0004_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
