# Generated by Django 3.2.15 on 2022-09-02 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api', '0004_auto_20220902_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watcher_issue_id', to='ticket_api.issue')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watcher_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
