# Generated by Django 3.2.15 on 2022-08-31 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api', '0005_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticket_api.role'),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_time', models.IntegerField()),
                ('assignee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='ticket_api.user')),
                ('reporter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='ticket_api.user')),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticket_api.issuestatus')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticket_api.issuetype')),
            ],
        ),
    ]
