# Generated by Django 3.2.15 on 2022-08-31 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api', '0007_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIssueMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='ticket_api.issue')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='ticket_api.project')),
            ],
        ),
    ]
