# Generated by Django 3.2.15 on 2022-09-01 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api', '0008_projectissuemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_field', models.CharField(max_length=20)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('issue_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='issue_id', to='ticket_api.issue')),
            ],
        ),
    ]
