# Generated by Django 3.2.15 on 2022-09-01 12:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api', '0009_eventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='ticket_api.user')),
                ('issue_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_issue_id', to='ticket_api.issue')),
            ],
        ),
    ]
